### ISSUE TITLE
How do I build portfolio?

### ISSUE THREAD

**Issue by adrkable** [nitobuendia/finance-tracker#9]
Hey Nito 

Excited to try your finance-tracker but it's not clear to me how to build a portfolio or add assets. Here's a screenshot of what the web app looks like loaded https://imgur.com/a/ENoQ1gj

Any pointers on how to get started or where I went wrong?

- adrkable

**Comment by adrkable** [comment]
Figured it out using Rest API calls.

**Comment by nitobuendia** [comment]
Happy you were able to find the calls and use them. I know both the UI and documentation are not very good (I created this mainly for myself).

While you have figured it out, I am happy to provide the Postman calls for all the API endpoints. Would that be helpful?

**Comment by adrkable** [comment]
I'll accept all the help I can get, thanks in advance!

**Comment by nitobuendia** [comment]
@adrkable Here you go: https://documenter.getpostman.com/view/7379488/Szt789gi?version=latest


I will add some explanation to the README as well.
